// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwibpnUwGyku3hPVtFySs8UoWbKNhjzpE',
    appId: '1:601012198978:web:c65221cc44c66afa0c57db',
    messagingSenderId: '601012198978',
    projectId: 'tick-detection',
    authDomain: 'tick-detection.firebaseapp.com',
    storageBucket: 'tick-detection.firebasestorage.app',
    measurementId: 'G-FV7DW486XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2TwgLMJRJgRtM6vNrM7KqvQoMAwn2fiY',
    appId: '1:601012198978:android:5820c5155c3ddde50c57db',
    messagingSenderId: '601012198978',
    projectId: 'tick-detection',
    storageBucket: 'tick-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwU0DneNG857dZPbAIB-LpUFcX5SxPjdQ',
    appId: '1:601012198978:ios:13bc3c02a267b7510c57db',
    messagingSenderId: '601012198978',
    projectId: 'tick-detection',
    storageBucket: 'tick-detection.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwU0DneNG857dZPbAIB-LpUFcX5SxPjdQ',
    appId: '1:601012198978:ios:13bc3c02a267b7510c57db',
    messagingSenderId: '601012198978',
    projectId: 'tick-detection',
    storageBucket: 'tick-detection.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwibpnUwGyku3hPVtFySs8UoWbKNhjzpE',
    appId: '1:601012198978:web:1723f0ba147199e90c57db',
    messagingSenderId: '601012198978',
    projectId: 'tick-detection',
    authDomain: 'tick-detection.firebaseapp.com',
    storageBucket: 'tick-detection.firebasestorage.app',
    measurementId: 'G-GB5RXPM01Z',
  );
}
